### ISSUE TITLE
Folder copy from S3 to Local throwing "EISDIR" exception.

### ISSUE THREAD

**Issue by graham-** [jabrythehutt/fs-s3#2]
I've run into an issue whereby copying from an `S3` folder to a `Local` folder fails with an `"EISDIR: illegal operation on directory"` error.

Having a very quick look through the code, it seems that the `S3` to `Local` functionality may be trying to stream (essentially) folders from `S3` to `Local`, causing `Node` to issue the exception. The `S3` source has several nested folders with files at the end.

**Comment by jabrythehutt** [comment]
Thanks for reporting this Graham, I'll try to re-create this in a test and work on a fix

**Comment by graham-** [comment]
Thank you so much for the super quick reply! :smile: If you need any other details, just let me know.

**Comment by graham-** [comment]
The `S3` source looks a little like this: `/source/sub-folder/sub-sub-folder/data.json`, and I'm attempting to copy from `S3` using `/source` as the `key`, with the destination being a folder on the local filesystem.

So more or less: `S3/source` to `FS/destination`.

**Comment by jabrythehutt** [comment]
@graham- I've published a fix for this issue, please feel free to re-open if it doesn't work for you

**Comment by graham-** [comment]
Awesome turnaround, thank you! :smile: 

Will let you know if I bump into any issues. :+1:
